### ISSUE TITLE
boltzcli: autoswap setup unexpected "invalid swap type" error

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-client#112]
Not sure how I managed to get into this state, I tested a couple of configurations without ever activating autoswap before I got here.

![image](https://github.com/BoltzExchange/boltz-client/assets/19181985/6bb0db07-192a-4c9e-ab07-113ce5c548f1)

**Comment by kilrau** [comment]
My `autoswap.toml`:
```toml
acceptZeroConf = false
budget = "100000"
budgetInterval = "604800"
channelPollInterval = "30"
currency = "LBTC"
enabled = false
failureBackoff = "86400"
maxBalance = "0"
maxBalancePercent = 75.0
maxFeePercent = 1.0
maxSwapAmount = "0"
minBalance = "0"
minBalancePercent = 25.0
perChannel = false
staticAddress = ""
swapType = ""
wallet = ""
```
